### ISSUE TITLE
Is stork published to npm?

### ISSUE THREAD

**Issue by styfle** [jameslittle230/stork#129]
Step 2 from the [web instructions](https://stork-search.net/docs/interface) shows an embedded script:

```html
<script src="https://files.stork-search.net/stork.js"></script>
```

1. Is this JS published to npm? What if we want to add it as a dependency to our project so its versioned?
2. Do the .wasm file and .js file need to be shipped together? Ideally the wasm file could be published to npm as well.

**Comment by jameslittle230** [comment]
Hi @styfle! Thanks for writing in.

Stork is not on NPM today. I hope to be able to publish it on NPM at some point, but I've focused on the minimal-installation use case for the 1.0.0 launch. I agree that being able to version the project would be useful for Stork's users.

NPM publishing is made complex by loading the WASM into the Javascript runtime. The Javascript library must reference a specific version of the WASM binary, and today those are published together when a new version is released. Loading Stork from NPM would either require that:

1. The JS load the WASM from the Stork CDN, or
2. The user host the WASM on their own server.

The first option would require uploading versioned copies of the WASM binary to the Stork CDN, which is possible, just not built into the publishing pipeline today. This would solve versioning, but would not be an appropriate solution for people who want to self-host Stork.

The second option would be equivalent to self-hosting Stork. I've outlined a few of the challenges with that method in the comments of #101, but I haven't ruled out self-hosting entirely.

Ultimately, this is something I want to build, but it will require significant planning and building.

Let me know if you have any more questions!

Best,
James

**Comment by styfle** [comment]
@jameslittle230 Another question for you:

Can I write my own JS to interact with the wasm file? I want to handle my own HTML and CSS, not using the defaults.

```js
WebAssembly.instantiateStreaming(fetch('/stork.wasm'), {}).then(obj => {
  console.log(obj.instance.exports)
})
```

This seems to fail so I'm hoping you could provide the code to call into the wasm file (something thats not minified 🙂)

**Comment by styfle** [comment]
I inspected the storm.wasm file and found that I need to specify the imports object.

But both calls to register and search don't work.

```js
     const imports = {
          wbg: {
            __wbg_new_59cb74e423758ede: () => {
            },
            __wbg_stack_558ba5917b466edd: (e, t) => {
            },
            __wbg_error_4bb6c2a97407129a: (e, t) => {
            },
            __wbindgen_object_drop_ref: (e) => {
            }
          }
      };
      
      const { instance: { exports } } = await WebAssembly.instantiateStreaming(fetch('/stork.wasm'), imports);
      const name = '/index.st'
      const res = await fetch(name)
      const buf = await res.arrayBuffer()
      exports.wasm_register_index(name, new Uint8Array(buff))
      const results = exports.wasm_search(name, 'test');
      // results is undefined :(
```

**Comment by jameslittle230** [comment]
@styfle -

Building one's own JavaScript on top of Stork's WASM API isn't likely going to be a supported way of working with Stork; the two are meant to work together to manage the registration of an index.

The WASM API itself (including all the `wbg` methods) is built by [wasm-pack](https://github.com/rustwasm/wasm-pack). In order to work with the WASM API, you'll likely have to build Stork from source. If you run `yarn build:wasm:prod`, wasm-pack will build an NPM module that includes a WASM binary and an ES6 module in `stork.js`. That ES6 module includes all the boilerplate necessary to communicate between Javascript and WASM. If you wanted to handle the DOM yourself today, you'd likely need to build the ES6 module from source and effectively replicate the [Javascript parts of Stork](https://github.com/jameslittle230/stork/tree/master/js).

I sympathize that not everyone wants Stork to manage the DOM for them -- this is one of the reasons I've been seeing bugs on the project's website. Instead of making the WASM API easier to work with though, I plan on exposing more Javascript API methods. Today. `stork.register()` downloads the WASM blob, downloads the index, and hooks into the DOM. In the future, I want to include four new JS methods on the `stork` object:

- One that downloads the WASM blob
- One that downloads the index and saves it into the WASM runtime's memory
- One that hooks into DOM elements
- One that lets you search the saved index from Javascript, in case you want to build your own DOM management

This project will likely be the next thing I tackle, given the amount of feedback I've been receiving about working with Stork's Javascript library since the project's launch.

Hope that helps,
James

**Comment by jameslittle230** [comment]
Self-hosting support solves a lot of the immediate user need here, but Stork still isn't on NPM.

Unfortunately, hosting a run-in-the-browser, bundle-with-webpack type Javascript package on NPM isn't in my area of expertise, so I'm adding the `help-wanted` label with the hope that someone else can submit a PR that would let folks `npm install stork-search` and have it do the right thing.

Let me know if anyone's interested in working on this. I'd give more guidance, but honestly, if you know how to do this, you probably know more than me about the experience of installing and loading the library than I do.

**Comment by styfle** [comment]
It looks like you already published to npm here: https://www.npmjs.com/package/stork-search

Although it currently fails during install with the following:

```
error Package "stork-search" refers to a non-existing file '"./myapp/storkserach/pkg"'.
```

Besides `cargo build` and `yarn build`, what other prep did you do to publish to npm vs your own website?

**Comment by jameslittle230** [comment]
The WASM library has to be built first, before running `yarn install`.

Running `yarn build` should get you what you want, I think.

**Comment by styfle** [comment]
@jameslittle230 Theres a paradox here.

You can't run `yarn build` until you have dependencies.

```
error Command "webpack" not found.
```

But you can't run `yarn install` until the wasm pkg is built.

```
error Package "stork-search" refers to a non-existing file '"./myapp/storkserach/pkg"'.
```

**Comment by jameslittle230** [comment]
Yup, that's not ideal.

I think I fixed that last night in this commit: https://github.com/jameslittle230/stork/commit/5d29d9bdba2eee57389885f4bd1759f5bb9baa76#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2b

**Comment by styfle** [comment]
@jameslittle230 That didn't work, still fails with `Package "stork-search" refers to a non-existing file`.

You can reproduce by doing the following:

```
git clone https://github.com/jameslittle230/stork
cd stork
./scripts/build.sh
```

**Comment by jameslittle230** [comment]
Build scripts that rely on ordering are so tricky to develop on, since building the project slows down the debugging loop. Thanks for being patient.

I think I (really truly) fixed this with ac555b8786b8351f0f27732e3cf127dfae8e7736 -- I'm now able to build the entire project in a clean VM with the above reproduction commands. Let me know if it's working for you now.

**Comment by styfle** [comment]
That does indeed work now 👍 

What's the difference between `./pkg/stork_bg.wasm` and `./dist/stork.wasm`?

Does the `bg` represent something?

**Comment by ThatGuySam** [comment]
Microlink hosts an npm package for the youtube-dl binaries called youtube-dl-exec

It looks like they use a `postinstall` node script to download the binary from the official distribution channels: 
https://github.com/microlinkhq/youtube-dl-exec/blob/master/scripts/postinstall.js

It gets triggered from [package.json](https://github.com/microlinkhq/youtube-dl-exec/blob/36dffe1d75a327b7e02383a353291a8cab9d1e33/package.json#L68), I assume, when the user installs the package on their system. 

Then they just wrap the CLI commands into an exportable function via [execa](https://github.com/microlinkhq/youtube-dl-exec/blob/36dffe1d75a327b7e02383a353291a8cab9d1e33/src/index.js#L17)

Theoretically, you should be able to match the different target-specific binary URLs to Nonde's `process.platform` like so: 
```js
function getBinaryUrl () {
    // macOS
    if ( process.platform === 'darwin' ) {
        return 'https://files.stork-search.net/releases/v1.4.2/stork-macos-10-15'
    }

    // Linux - default
    return 'https://files.stork-search.net/releases/v1.4.2/stork-amazon-linux'
}
```

**Comment by ThatGuySam** [comment]
We can also pull the latest release assets, such as the `stork.wasm` and `stork-ubuntu-20-04`, from GitHub the same way `youtube-dl-exec` does: 
https://api.github.com/repos/jameslittle230/stork/releases?per_page=1

**Comment by jil-stripe** [comment]
Ah, that's brilliant! I'll look into that!

**Comment by styfle** [comment]
You can use `optionalDependencies` where each one represents a different binary for a different platform.

See Next.js for an example of `optionalDependencies`:

https://unpkg.com/browse/next@12.1.6/package.json

And look at one of the deps to see how `os` and `cpu` are used:

https://unpkg.com/browse/@next/swc-darwin-x64@11.1.2/package.json

**Comment by jameslittle230** [comment]
(I had responded from an incorrect Github account earlier)

This is great - thanks, both, for outlining a path forward here. I think this will work as expected, and I'll start exploring this as soon as I can.

**Comment by ThatGuySam** [comment]
@jameslittle230 Here's an in-progress download script that's working on macOS and Netlify Ubuntu: 
https://github.com/ThatGuySam/doesitarm/blob/7318de945d754433add70896777b6a56b007c594/helpers/stork/executable.js

For some reason, it gives me trouble when I try to run the executable to build the index from Node so I ended up running it via the [package.json](https://github.com/ThatGuySam/doesitarm/blob/7318de945d754433add70896777b6a56b007c594/package.json#L36)

**Comment by strogonoff** [comment]
> * A package that **builds search indexes from the Node runtime.** This package would be installed as part of a JS-based static site generator (Next.js, Gatsby, 11ty).

I’d like to add to that, the Node part is optional: just JS runtime. (I’m working on a project where it’d be desirable to let users preview built site from within the headless CMS that runs in browser. It has access to Web workers and can obviously load WASM, as browsers do, but can’t use Node’s environment.)

It seems natural to separate it into runtime-independent code that returns the index blob, and a Node CLI that uses `fs` et al. to write the blob somewhere on disk. Those who want it can use the former without the latter, and do something else with the index blob.
